version: '3.8'

services:
  mockapi:
    image: mockapi:1.0
    ports:
      - "80:80"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
